#######################################################################################
# Configuration for the experiment

#######################################################################################
source_id                   : DUMMY-MODEL
experiment_id               : piControl
variant_label               : r1i1p1f1
grid_label                  : g999
version                     : v20260601

