#######################################################################################
# Configuration for the experiment

#######################################################################################

experiment_id               : piControl
variant                     : r1i1p1f1
version                     : v20260601

